# Generated by Django 4.0.3 on 2022-04-02 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=1024, unique=True)),
                ('domain', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedKeywords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queryKeyword', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatedKeywords', to='searchEngine.keywords')),
                ('relatedKeywords', models.ManyToManyField(related_name='parentKeyword', to='searchEngine.keywords')),
            ],
        ),
        migrations.CreateModel(
            name='LinkPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchEngine.link')),
                ('queryKeyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchEngine.keywords')),
            ],
        ),
    ]
